name: ci-master
on:
  workflow_dispatch:
  push:
    branches:
    - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - uses: actions/cache@v1
      env:
        cache-name: m2
      with:
        path: ~/.m2/repository
        key: ${{ env.cache-name }}-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ env.cache-name }}-
    - uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: environment
      run: |
          APP_SHA=$(git rev-parse --short ${GITHUB_SHA});
          APP_REV=$(git rev-list --tags --max-count=1);
          APP_TAG=$(git describe --tags ${APP_REV} 2> /dev/null || echo 0.0.0);
          APP_VERSION=${APP_TAG}-${APP_SHA};
          echo "APP_SHA=${APP_SHA}" >> ${GITHUB_ENV};
          echo "APP_TAG=${APP_TAG}" >> ${GITHUB_ENV};
          echo "APP_VERSION=${APP_VERSION}" >> ${GITHUB_ENV};
    - name: mvn version
      run: >-
        mvn versions:set
        --batch-mode
        --define newVersion="${APP_VERSION};

    - name: mvn deploy
      run: mvn --batch-mode deploy
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: mvn sonar
      run: |
        mvn --batch-mode verify sonar:sonar \
        -Dsonar.login=${SONAR_TOKEN} \
        -Dsonar.host.url=${SONAR_URL} \
        -Dsonar.organization=${GITHUB_REPOSITORY_OWNER} \
        -Dsonar.projectKey=${GITHUB_REPOSITORY/\//_}
      env:
        SONAR_URL: https://sonarcloud.io
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - uses: actions/upload-artifact@v1
      with:
        name: target
        path: target
    - name: docker build
      run: |
        docker build \
        --tag docker.pkg.github.com/${GITHUB_REPOSITORY}/${ARTIFACT_ID}:${VERSION} \
        --tag ${TRUSTED_URL}/${TRUSTED_REPOSITORY}/${ARTIFACT_ID}:${VERSION} \
        .
      env:
        TRUSTED_URL: ${{ secrets.TRUSTED_URL }}
        TRUSTED_REPOSITORY: ${{ secrets.TRUSTED_REPOSITORY }}
    - name: docker push github
      run: |
        echo ${GITHUB_TOKEN} | docker login docker.pkg.github.com -u ${GITHUB_REPOSITORY_OWNER} --password-stdin
        docker push docker.pkg.github.com/${GITHUB_REPOSITORY}/${ARTIFACT_ID}:${VERSION}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: docker push trusted
      run: |
        echo ${TRUSTED_TOKEN} | docker login ${TRUSTED_URL} -u ${TRUSTED_USER} --password-stdin
        export DOCKER_CONTENT_TRUST=1
        export DOCKER_CONTENT_TRUST_SERVER=${TRUSTED_SERVER_URL}
        export DOCKER_CONTENT_TRUST_ROOT_PASSPHRASE=${TRUSTED_TOKEN}
        export DOCKER_CONTENT_TRUST_REPOSITORY_PASSPHRASE=${TRUSTED_TOKEN}
        gpg --quiet --batch --yes --decrypt --passphrase=${TRUSTED_KEY} \
        --output trusted.key trusted.key.gpg
        chmod 600 trusted.key
        docker trust key load trusted.key --name user
        docker trust sign ${TRUSTED_URL}/${TRUSTED_REPOSITORY}/${ARTIFACT_ID}:${VERSION}
        docker push ${TRUSTED_URL}/${TRUSTED_REPOSITORY}/${ARTIFACT_ID}:${VERSION}
      env:
        TRUSTED_KEY: ${{ secrets.TRUSTED_KEY }}
        TRUSTED_URL: ${{ secrets.TRUSTED_URL }}
        TRUSTED_SERVER_URL: ${{ secrets.TRUSTED_SERVER_URL }}
        TRUSTED_REPOSITORY: ${{ secrets.TRUSTED_REPOSITORY }}
        TRUSTED_USER: ${{ secrets.TRUSTED_USER }}
        TRUSTED_TOKEN: ${{ secrets.TRUSTED_TOKEN }}
